export default [
    { id: 1, category: 'drinks', name: 'Expresso', price: 1.5 },
    { id: 2, category: 'drinks', name: 'Cappuccino', price: 2.5 },
    { id: 3, category: 'drinks', name: 'Latte', price: 3.5 },
    { id: 4, category: 'drinks', name: 'Tea', price: 2.5 },
    { id: 5, category: 'drinks', name: 'Hot Chocolate', price: 2.5 },
    { id: 6, category: 'drinks', name: 'Iced coffee', price: 1.5 },
    { id: 7, category: 'drinks', name: 'Americano', price: 2.5 },
    { id: 8, category: 'drinks', name: 'Macchiato', price: 2.5 },
    { id: 9, category: 'drinks', name: 'Venice Coffee', price: 2.5 },
    { id: 10, category: 'drinks', name: 'Coffee Mocca', price: 1.5 },
    { id: 11, category: 'drinks', name: 'Coffee with Milk', price: 1.5 },
    { id: 12, category: 'drinks', name: 'Long Black', price: 1.5 },
    { id: 13, category: 'drinks', name: 'Chocolate Coffee', price: 1.5 },
    { id: 14, category: 'snacks', name: 'Chips', price: 1.5 },
    { id: 15, category: 'snacks', name: 'Cookies', price: 2.5 },
    { id: 16, category: 'snacks', name: 'Candy', price: 3.5 },
    { id: 17, category: 'snacks', name: 'Ice Cream', price: 2.5 },
    { id: 18, category: 'snacks', name: 'Hot Dog', price: 2.5 },
    { id: 19, category: 'snacks', name: 'Chips with Cheese', price: 1.5 },
    { id: 20, category: 'snacks', name: 'Chips with Cheese and Bacon', price: 1.5 },
    { id: 21, category: 'snacks', name: 'Chips with Cheese and Ham', price: 1.5 },
    { id: 22, category: 'snacks', name: 'Hamburger', price: 1.5 },
    { id: 23, category: 'snacks', name: 'Cheese Burger', price: 1.5 },
    { id: 24, category: 'snacks', name: 'Pizza', price: 1.5 },
    { id: 25, category: 'snacks', name: 'Nuggets', price: 1.5 }
]