module.exports = [
    { id: 1, category: "burgers", emoji: '🍔', name: "Big Mac", price: 3, image: "https://picsum.photos/300/200" },
    { id: 2, category: "burgers", emoji: '🍔', name: "McChicken", price: 2, image: "https://picsum.photos/300/200" },
    { id: 3, category: "burgers", emoji: '🍔', name: "McWrap", price: 3, image: "https://picsum.photos/300/200" },
    { id: 4, category: "burgers", emoji: '🍔', name: "McDouble", price: 4, image: "https://picsum.photos/300/200" },
    { id: 6, category: "burgers", emoji: '🍔', name: "Wrapper", price: 2, image: "https://picsum.photos/300/200" },
    { id: 7, category: "burgers", emoji: '🍔', name: "Cheeseburger", price: 3, image: "https://picsum.photos/300/200" },
    { id: 8, category: "burgers", emoji: '🍔', name: "Slugburger", price: 4, image: "https://picsum.photos/300/200" },
    { id: 9, category: "burgers", emoji: '🍔', name: "McVeggie", price: 3, image: "https://picsum.photos/300/200" },
    { id: 10, category: "burgers", emoji: '🍔', name: "Slider", price: 4, image: "https://picsum.photos/300/200" },
    { id: 11, category: "burgers", emoji: '🍔', name: "Hamburger", price: 3, image: "https://picsum.photos/300/200" },
    { id: 11, category: "burgers", emoji: '🍔', name: "Tenderburger", price: 4, image: "https://picsum.photos/300/200" },
    { id: 12, category: "snacks", emoji: '🍟', name: "Chips", price: 2, image: "https://picsum.photos/300/200" },
    { id: 13, category: "snacks", emoji: '🍟', name: "Nuggets", price: 3, image: "https://picsum.photos/300/200" },
    { id: 14, category: "snacks", emoji: '🍟', name: "Popcorn", price: 2, image: "https://picsum.photos/300/200" },
    { id: 15, category: "snacks", emoji: '🍟', name: "Candy", price: 3, image: "https://picsum.photos/300/200" },
    { id: 16, category: "snacks", emoji: '🍟', name: "Fries", price: 2, image: "https://picsum.photos/300/200" },
    { id: 17, category: "snacks", emoji: '🍟', name: "Onion Rings", price: 3, image: "https://picsum.photos/300/200" },
    { id: 18, category: "snacks", emoji: '🍟', name: "Nuts", price: 2, image: "https://picsum.photos/300/200" },
    { id: 19, category: "snacks", emoji: '🍟', name: "Nachos", price: 3, image: "https://picsum.photos/300/200" },
    { id: 20, category: "pizzas", emoji: '🍕', name: "Margarita", price: 3, image: "https://picsum.photos/300/200" },
    { id: 21, category: "pizzas", emoji: '🍕', name: "Pepperoni", price: 4, image: "https://picsum.photos/300/200" },
    { id: 22, category: "pizzas", emoji: '🍕', name: "Hawaiian", price: 3, image: "https://picsum.photos/300/200" },
    { id: 23, category: "pizzas", emoji: '🍕', name: "Veggie", price: 4, image: "https://picsum.photos/300/200" },
    { id: 24, category: "desserts", emoji: '🧁', name: "Ice Cream", price: 3, image: "https://picsum.photos/300/200" },
    { id: 25, category: "desserts", emoji: '🧁', name: "Cake", price: 2, image: "https://picsum.photos/300/200" },
    { id: 26, category: "desserts", emoji: '🧁', name: "Pie", price: 3, image: "https://picsum.photos/300/200" },
    { id: 27, category: "desserts", emoji: '🧁', name: "Cupcake", price: 4, image: "https://picsum.photos/300/200" },
    { id: 28, category: "desserts", emoji: '🧁', name: "Cookie", price: 3, image: "https://picsum.photos/300/200" },
    { id: 29, category: "desserts", emoji: '🧁', name: "Brownie", price: 4, image: "https://picsum.photos/300/200" },
    { id: 30, category: "desserts", emoji: '🧁', name: "Tiramisu", price: 3, image: "https://picsum.photos/300/200" },
    { id: 31, category: "desserts", emoji: '🧁', name: "Muffin", price: 4, image: "https://picsum.photos/300/200" },
    { id: 32, category: "desserts", emoji: '🧁', name: "Mousse", price: 3, image: "https://picsum.photos/300/200" },
    { id: 33, category: "desserts", emoji: '🧁', name: "Apple", price: 4, image: "https://picsum.photos/300/200" },
    { id: 34, category: "desserts", emoji: '🧁', name: "Cherry", price: 3, image: "https://picsum.photos/300/200" },
    { id: 35, category: "desserts", emoji: '🧁', name: "Pineapple", price: 4, image: "https://picsum.photos/300/200" },
    { id: 36, category: "desserts", emoji: '🧁', name: "Strawberry", price: 3, image: "https://picsum.photos/300/200" },
    { id: 37, category: "desserts", emoji: '🧁', name: "Chocolate", price: 4, image: "https://picsum.photos/300/200" },
];